const js = require("@eslint/js");

module.exports = [
  // Ignore build outputs, vendored code, and docs
  {
    ignores: ["dist/", "node_modules/", "docs/", "coverage/", "playwright-report/", "test-results/"],
  },

  // Source files — browser environment, ES modules
  {
    ...js.configs.recommended,
    files: ["src/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        HTMLElement: "readonly",
        HTMLTemplateElement: "readonly",
        HTMLFormElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLTextAreaElement: "readonly",
        Element: "readonly",
        Node: "readonly",
        NodeList: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        KeyboardEvent: "readonly",
        MouseEvent: "readonly",
        DragEvent: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        DOMParser: "readonly",
        XMLSerializer: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        FormData: "readonly",
        Headers: "readonly",
        Request: "readonly",
        Response: "readonly",
        AbortController: "readonly",
        fetch: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        requestIdleCallback: "readonly",
        queueMicrotask: "readonly",
        performance: "readonly",
        console: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        atob: "readonly",
        btoa: "readonly",
        structuredClone: "readonly",
        Proxy: "readonly",
        Reflect: "readonly",
        WeakRef: "readonly",
        FinalizationRegistry: "readonly",
        crypto: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        DataTransfer: "readonly",
        ClipboardEvent: "readonly",
        getComputedStyle: "readonly",
        matchMedia: "readonly",
        DocumentFragment: "readonly",
        TreeWalker: "readonly",
        self: "readonly",
      },
    },
    rules: {
      // Relax rules that conflict with the project's established patterns
      "no-prototype-builtins": "off",
    },
  },

  // Config files and tests — Node.js environment, CommonJS
  {
    ...js.configs.recommended,
    files: [
      "*.config.js",
      "*.config.cjs",
      "build.js",
      "test-server.js",
      "babel.config.js",
      "commitlint.config.js",
      "__tests__/**/*.js",
      "__benchmarks__/**/*.js",
    ],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: {
        // Node globals
        module: "readonly",
        require: "readonly",
        exports: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        process: "readonly",
        console: "readonly",
        Buffer: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        // Jest globals
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        jest: "readonly",
      },
    },
  },
];
